# Configuración de golangci-lint para BCV Currency API
# Creado por AndrusCodex

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - vendor
  skip-files:
    - ".*_test.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  # Configuración de errcheck
  errcheck:
    check-type-assertions: true
    check-blank: true
    ignore: fmt:.*,io/ioutil:^Read.*

  # Configuración de gocyclo
  gocyclo:
    min-complexity: 15

  # Configuración de govet
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  # Configuración de golint
  revive:
    min-confidence: 0
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  # Configuración de goimports
  goimports:
    local-prefixes: gobcv

  # Configuración de misspell
  misspell:
    locale: US
    ignore-words:
      - bcv
      - venezuela
      - venezuelan

  # Configuración de lll
  lll:
    line-length: 120

  # Configuración de unused
  unused:
    check-exported: false

  # Configuración de unparam
  unparam:
    check-exported: false

  # Configuración de nakedret
  nakedret:
    max-func-lines: 30

  # Configuración de prealloc
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  # Configuración de gocritic
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  # Linters habilitados
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  # Linters deshabilitados
  disable:
    - asciicheck
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - goerr113
    - interfacer
    - maligned
    - nestif
    - prealloc
    - testpackage
    - wsl

issues:
  # Excluir algunos archivos de checks específicos
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gosec
        - dupl

    # Excluir algunos directorios
    - path: cmd/
      linters:
        - gochecknoinits

    # Excluir algunos linters para archivos específicos
    - path: main\.go
      linters:
        - gochecknoinits

  # Lista de reglas a excluir
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print.*|os\.(Un)?Setenv). is not checked

  # Cantidad máxima de issues del mismo tipo a mostrar
  max-issues-per-linter: 50

  # Cantidad máxima de issues de un archivo específico
  max-same-issues: 3

  # Mostrar solo issues nuevos
  new: false

  # Fix automático
  fix: false
